export {
  appendBlock,
  appendEvents,
  assertFact,
  corroborate,
  createSession,
  eidenticFunctions,
  eraseScope,
  expireFacts,
  getBlock,
  getBlockHistory,
  getBlocks,
  getDecision,
  getIdempotency,
  getSession,
  indexMemory,
  lastCheckpoint,
  listBlocks,
  listSessions,
  queryFacts,
  readEvents,
  recordCompletion,
  recordDecision,
  recordIntent,
  searchMemory,
  sweepExpired,
  upsertBlock,
  vectorDelete,
  vectorEraseScope,
  vectorList,
  vectorSearch,
  vectorUpsert,
  writeCheckpoint,
  type EidenticAuthorize,
  type EidenticFunctionsOptions,
} from "../server.js";
